# Generated by Django 6.0.2 on 2026-04-16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0004_alter_academy_founded_year"),
        ("players", "0003_remove_player_age_remove_player_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("home_score", models.PositiveIntegerField(default=0)),
                ("away_score", models.PositiveIntegerField(default=0)),
                ("competition", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("away_academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="away_matches", to="academies.academy")),
                ("home_academy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="home_matches", to="academies.academy")),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="MatchParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started", models.BooleanField(default=False)),
                ("minutes_played", models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ("goals", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participations", to="matches.match")),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="match_participations", to="players.player")),
            ],
            options={
                "ordering": ("match", "player"),
            },
        ),
        migrations.AddField(
            model_name="match",
            name="players",
            field=models.ManyToManyField(related_name="matches", through="matches.MatchParticipation", to="players.player"),
        ),
        migrations.AddConstraint(
            model_name="matchparticipation",
            constraint=models.UniqueConstraint(fields=("match", "player"), name="unique_match_participation"),
        ),
    ]
