# Generated by Django 6.0.2 on 2026-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
