# Generated by Django 6.0.2 on 2026-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_academy_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academy',
            options={},
        ),
        migrations.AddField(
            model_name='academy',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
