# Generated by Django 6.0.2 on 2026-03-16 16:37

import academies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_alter_academy_options_academy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='founded_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800), academies.models.validate_max_year]),
        ),
    ]
