# Generated by Django 6.0.2 on 2026-02-21 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('skill', models.CharField(choices=[('ft', 'First Touch'), ('db', 'Dribbling'), ('ps', 'Passing'), ('fn', 'Finishing'), ('bc', 'BallControl'), ('cr', 'Crossing'), ('sep', 'SetPieces'), ('ph', 'Physical'), ('ac', 'Acceleration'), ('sp', 'SprintSpeed'), ('ag', 'Agility'), ('sta', 'Stamina'), ('st', 'Strength'), ('b', 'Balance'), ('r', 'Recovery'), ('mt', 'MentalStrength'), ('dm', 'DecisionMaking'), ('c', 'Concentration'), ('l', 'Leadership'), ('con', 'Confidence'), ('p', 'Positioning'), ('d', 'DefensiveAwareness'), ('g', 'GameReading')], max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ScoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_name', models.CharField(max_length=60)),
                ('report_date', models.DateField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('recommendation', models.CharField(choices=[('sign', 'Sign'), ('monitor', 'Monitor'), ('reject', 'Reject')], default='monitor', max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='players.player')),
                ('skills', models.ManyToManyField(blank=True, related_name='reports', to='scouting.skill')),
            ],
            options={
                'ordering': ('-report_date',),
            },
        ),
    ]
