# Generated by Django 6.0.2 on 2026-02-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutreport',
            name='recommendation',
            field=models.CharField(choices=[('s', 'Sign'), ('m', 'Monitor'), ('r', 'Reject')], default='monitor', max_length=10),
        ),
    ]
