# Generated by Django 6.0.2 on 2026-02-23 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoutreport',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='scoutreport',
            name='report_date',
        ),
        migrations.AddField(
            model_name='scoutreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoutreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
