# Generated by Codex on 2026-03-16

from django.db import migrations

from scouting.choices import PlayerSkills


def seed_skills(apps, schema_editor):
    Skill = apps.get_model("scouting", "Skill")
    for value, label in PlayerSkills.choices:
        Skill.objects.get_or_create(skill=value, defaults={"name": label})


def unseed_skills(apps, schema_editor):
    Skill = apps.get_model("scouting", "Skill")
    skill_values = [value for value, _ in PlayerSkills.choices]
    Skill.objects.filter(skill__in=skill_values).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("scouting", "0002_alter_scoutreport_options_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_skills, unseed_skills),
    ]

