# Generated by Codex on 2026-03-16

from django.db import migrations


def rename_defensive_awareness_skill(apps, schema_editor):
    Skill = apps.get_model("scouting", "Skill")
    Skill.objects.filter(skill="d").update(name="Defence")


def unrename_defensive_awareness_skill(apps, schema_editor):
    Skill = apps.get_model("scouting", "Skill")
    Skill.objects.filter(skill="d").update(name="DefensiveAwareness")


class Migration(migrations.Migration):

    dependencies = [
        ("scouting", "0003_seed_skills"),
    ]

    operations = [
        migrations.RunPython(
            rename_defensive_awareness_skill,
            unrename_defensive_awareness_skill,
        ),
    ]
