# Generated by Codex on 2026-03-17

from django.db import migrations, models


def rename_defensive_awareness_skill(apps, schema_editor):
    Skill = apps.get_model("scouting", "Skill")
    Skill.objects.filter(skill="d").update(name="Defence")


def unrename_defensive_awareness_skill(apps, schema_editor):
    Skill = apps.get_model("scouting", "Skill")
    Skill.objects.filter(skill="d").update(name="DefensiveAwareness")


class Migration(migrations.Migration):

    dependencies = [
        ("scouting", "0003_seed_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill",
            field=models.CharField(
                choices=[
                    ("ft", "First Touch"),
                    ("db", "Dribbling"),
                    ("ps", "Passing"),
                    ("fn", "Finishing"),
                    ("bc", "BallControl"),
                    ("cr", "Crossing"),
                    ("sep", "SetPieces"),
                    ("ph", "Physical"),
                    ("ac", "Acceleration"),
                    ("sp", "SprintSpeed"),
                    ("ag", "Agility"),
                    ("sta", "Stamina"),
                    ("st", "Strength"),
                    ("b", "Balance"),
                    ("r", "Recovery"),
                    ("mt", "MentalStrength"),
                    ("dm", "DecisionMaking"),
                    ("c", "Concentration"),
                    ("l", "Leadership"),
                    ("con", "Confidence"),
                    ("p", "Positioning"),
                    ("d", "Defence"),
                    ("g", "GameReading"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(
            rename_defensive_awareness_skill,
            unrename_defensive_awareness_skill,
        ),
    ]
