# Generated by Django 6.0.2 on 2026-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_seed_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(choices=[('ft', 'First Touch'), ('db', 'Dribbling'), ('ps', 'Passing'), ('fn', 'Finishing'), ('bc', 'BallControl'), ('cr', 'Crossing'), ('sep', 'SetPieces'), ('ph', 'Physical'), ('ac', 'Acceleration'), ('sp', 'SprintSpeed'), ('ag', 'Agility'), ('sta', 'Stamina'), ('st', 'Strength'), ('b', 'Balance'), ('r', 'Recovery'), ('mt', 'MentalStrength'), ('dm', 'DecisionMaking'), ('c', 'Concentration'), ('l', 'Leadership'), ('con', 'Confidence'), ('p', 'Positioning'), ('d', 'Defence'), ('g', 'GameReading')], max_length=50),
        ),
    ]
