# Generated by Codex on 2026-03-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scouting", "0004_alter_skill_skill"),
        ("scouting", "0004_rename_defensive_awareness_skill"),
    ]

    operations = []
