# Generated by Codex on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scouting", "0004_skill_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="scoutreport",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="reports", to="scouting.tag"),
        ),
    ]
