# Generated by Django 6.0.2 on 2026-02-21 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=10)),
                ('dominant_foot', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('both', 'both')], max_length=10)),
                ('potential', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='academies.academy')),
            ],
            options={
                'ordering': ('-potential', 'name'),
            },
        ),
    ]
