# Generated by Django 6.0.2 on 2026-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='players', to='scouting.skill'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('academy', 'name', 'birth_date'), name='unique_player'),
        ),
    ]
